hostname: "shipping.ijmacd.com"
appVersion: ""
web:
  replicaCount: 1
  repository:
    image: docker.io/ijmacd/shipping
  tls:
    enabled: false
  local:
    enabled: false
  resources:
    requests:
      cpu: 5m
      memory: 20Mi
    limits:
      memory: 20Mi
